### PR TITLE
calico out of box

### PR DESCRIPTION
**Pull request by wuxingzhong**
###  What this PR does 

Remove CNI  from source code.  

###  Why we need it

Sealer now installs calico using a template, but the template is [source code](https://github.com/alibaba/sealer/blob/main/guest/calico.go#L44) which is really not good.

Now sealer has the config feature, so we can completely not care about the CNI in source code, we treat it like a regular app.

So remove CNI from the source code is the first step.

I will put CNI  plugin in applications in the next step. 
 
For more information, see:  [calico out of box](https://github.com/alibaba/sealer/issues/401)

### CODE REVIEW

**Comment by justadogistaken** [comment]
@wuxingzhong Why would we remove the cni from sealer? Could you describe more details about it ?

**Comment by wuxingzhong** [comment]
> @wuxingzhong Why would we remove the cni from sealer? Could you describe more details about it ?

ok, I have changed the description.

**Comment by fanux** [comment]
@justadogistaken because #401

**Review by fanux — APPROVED** [review]

**Comment by jafardu** [comment]
add cilium

**Comment by jafardu** [comment]
> @justadogistaken because #401

add cilium

**Pull request merged**
