### PR TITLE
sea.hub cretificate problems

### LINKED ISSUE #1034: can not save sea.hub:5000 images when sealer build
#### What happened:
lQLPDhsG59thpSPNAiLNDSawv9btCoeAi6MB2_zLeQAGAA_3366_546

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shy-Xu**
### Does this pull request fix one issue?
Fixes #1034

### CODE REVIEW

**Comment by shy-Xu** [comment]
This PR still work in progress

**Comment by shy-Xu** [comment]
image
New problem:"x509: certificate signed by unknown authority"

**Review by fanux — APPROVED** [review]

**Comment by fanux** [comment]
https://stackoverflow.com/questions/50768317/docker-pull-certificate-signed-by-unknown-authority

**Comment by shy-Xu** [comment]
I support save images from sea.hub but I think it contains unsafe http request, so I comment those code.
And I suggest we don't support save images from sea.hub, because it's either unsafe or increases complexity and costs a lot

**Comment by fanux** [comment]
What if user has a private registry?

**Review by fanux — APPROVED** [review]

**Pull request merged**
