### PR TITLE
feature(main): add version

### PR DESCRIPTION
**Pull request by cuisongliu**

### CODE REVIEW

**Review by fanux — APPROVED** [review]
Add build command in makefile support set version informations

**Review by cuisongliu — COMMENTED** [review]
add makefile

**Comment by cuisongliu** [comment]
this feature need optimize, like k8s use env to set var.

**Comment by cuisongliu** [comment]
@fanux 
env: GIT_TAG  code version
        MULTI_PLATFORM_BUILD  all support platform build(linux and darwin)

**Review by fanux — APPROVED** [review]

**Pull request merged**
