### PR TITLE
bugfix: standardized the file permission perm as sealer created

### PR DESCRIPTION
**Pull request by kakaZhou719**
### Describe what this PR does / why we need it

Standardized the file permission perm as sealer created
default perm as below:

file : 0644, means owner can read and write it , group user and other user can only read it . so there is no need for sealer to write file as 755 perm .

dir:  0755, need to give "+x" perm ,it means sealer can enter this directory. so this will  solve the issue #165 

### Describe how you did it
Troubleshoot all file permissions in our sealer project, and set file as 644 perm, and dir as 755 perm.

### Describe how to verify it
change non-root user run sealer login 
image

### CODE REVIEW

**Comment by kakaZhou719** [comment]
link issue #165

**Review by justadogistaken — APPROVED** [review]
LGTM

**Comment by justadogistaken** [comment]
fix conflicts first

**Comment by fanux** [comment]
LGTM

**Pull request merged**
