### PR TITLE
Ssh bug fix

### PR DESCRIPTION
**Pull request by lllwan**

### CODE REVIEW

**Comment by fanux** [comment]
Maybe you can describe what the bug is?

**Review by fanux — APPROVED** [review]

**Comment by lllwan** [comment]
> Maybe you can describe what the bug is?

We encountered a special scenario: it is not allowed to use the default port 22 for SSH communication. It is found that even if I specify the actual port, sealer will still try to use port 22, resulting in failure of communication.

**Comment by bxy4543** [comment]
test apply

**Pull request merged**
