### PR TITLE
optimize: add image store

### PR DESCRIPTION
**Pull request by justadogistaken**
This PR is for unify the interface for image/layer/metadata to operate get/delete/save.
Try not to GetImage simply from a global func like: `utils.GetImageByID`. Get image by image store instead.
```
func GetImageByID(imageID string) (*v1.Image, error) {
	fileName := filepath.Join(common.DefaultImageDBRootDir, imageID+".yaml")

	var image v1.Image
	return &image, utils.UnmarshalYamlFile(fileName, &image)
}
```
未命名文件 (1)

### CODE REVIEW

**Comment by justadogistaken** [comment]
@touchuyht @fanux @kakaZhou719 @bxy4543 PTAL

**Review by bxy4543 — APPROVED** [review]

**Pull request merged**
